# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David White
email: me@wizardfrag.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Hey, I'm David White! I'm an Erlang software developer working on some really
  great things. In my spare time I do things with Minecraft.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wizardfrag.co.uk" # the base hostname & protocol for your site
twitter_username: davidgawhite
github_username:  wizardfrag

# Build settings
markdown: kramdown
