baseURL = 'https://wizardfrag.co.uk/'
languageCode = 'en-gb'
title = "David White"
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
theme = ["PaperMod"]
rsslimit = 20
pagination.pagerSize = 5

enableRobotsTXT = true

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[params]
author = "David White"
description = "Software developer and hobbyist game developer"
keywords = ["Blog", "Portfolio", "Gamedev"]

[params.homeInfoParams]
Title = "Hi there! 👋🏻"
Content = """
I'm David, a full time software developer and hobbyist game developer.

I'm currently working as a software engineer at [prima](https://helloprima.com)!
"""

[[params.socialIcons]]
name = "Bluesky"
url = "https://bsky.app/profile/wizardfrag.uk"

[[params.socialIcons]]
name = "Mastodon"
url = "https://mstdn.social/@wizardfrag"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/wizardfrag"
